services:
  - type: web
    name: fcc-backend-v2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/app.py
    envVars:
      - key: FLASK_ENV
        value: production
